/**:
  ros__parameters:
    robot_type: "UGV_WHEELED"
    model_name: "turtlebot3_burger"
    
    # supported_tasks: ["SEARCH", "NAVIGATE"]
    
    capabilities:
      MOBILITY: 0.6
      VISION: 0.0
      NETWORK: 1.0
      BATTERY: 1.0

    thresholds:
      MOBILITY: 0.3
      VISION: 0.0
      NETWORK: 0.4
      BATTERY: 0.15

    fault_impacts:
      mobility_failure: 0.0
      vision_failure: 0.1
      network_failure: 0.0
      battery_failure: 0.5

    hardware:
      bringup_package: "turtlebot3_bringup"
      bringup_launch: "robot.launch.py"
      env_vars:
        TURTLEBOT3_MODEL: "burger"
    
    nav2:
      enabled: false
      use_sim_time: false
      map_yaml: "/"
      params_file: "tb3_nav2_params.yaml"
      initial_pose:
        x: 0.0
        y: 0.0
        yaw_degrees: 0.0

    telemetry:
      has_battery: true
      battery_topic: "battery_state"
      battery_v_max: 12.6
      battery_v_min: 11.1
      
      watchdogs:
        topics: ["odom", "scan"]
        types: ["nav_msgs.msg.Odometry", "sensor_msgs.msg.LaserScan"]
        capabilities: ["MOBILITY", "VISION"]
        timeouts: [2.0, 2.0]